apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  type: NodePort
  ports:
    - name: http
      port: 8200
      targetPort: vault
      nodePort: 32000
  selector:
    app: vault
