name: Destroy Vault Terraform

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: [self-hosted, macos]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.5"

      - name: Destroy Vault
        run: bash scripts/terraform-destroy.sh
